<!DOCTYPE html>
<html>
<head>
  <title>Yossi's State Machine</title>
  <style>
    .container {
      text-align: center;
      margin-top: 50px;
    }
  </style>
  <script>
    function generateRandomCombination() {
      const words = ['ads', 'without preview', 'client', 'creative', 'gallery', 'elements', 'custom', 'tags','amantos', 'federal', 'similarity','analytics', 'with preview', 'with reason','without reason','notion','chips','evyatar','content switch','partner','evyatar','chips'];
      const randomIndex1 = Math.floor(Math.random() * words.length);
      let randomIndex2 = Math.floor(Math.random() * words.length);
      while (randomIndex2 === randomIndex1) {
        randomIndex2 = Math.floor(Math.random() * words.length);
      }
      const combination = words[randomIndex1] + ' ' + words[randomIndex2];

      const resultElement = document.getElementById('result');
      resultElement.textContent = combination;
    }
  </script>
</head>
<body>
  <div class="container">
    <img src="https://media.licdn.com/dms/image/C4D03AQEpdmRx6H1glA/profile-displayphoto-shrink_400_400/0/1661778453512?e=1691625600&v=beta&t=nwO_tNB7u1XP0l74RSJmvNTl6a98TWWG3HWxEXECoRg" alt="Person Image">
    <br>
    <button onclick="generateRandomCombination()">Yossi's state machine</button>
    <h1 id="result"></h1>
  </div>
</body>
</html>
